# In this Docker Compose example, we only fire up the services required for local development.
# This is not advised for production use as it exposes ports to the database insecurely.
# If you're looking for a production-ready Docker Compose file, check out the `traefik.yml` file.

services:
  # Database (MySQL)
  mysql:
    image: mysql:8.4.4
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - mysql_data:/home/rodrigo/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-reactive-finances}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-mysql}

  # Adminer (for database management)
  adminer:
    image: shyim/adminerevo:latest
    restart: unless-stopped
    ports:
      - 5555:8080
    environment:
      ADMINER_DEFAULT_DRIVER: mysql
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DEFAULT_USER: ${MYSQL_USER:-root}
      ADMINER_DEFAULT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysql}
      ADMINER_DEFAULT_DB: ${MYSQL_DATABASE:-reactive-finances}

volumes:
  mysql_data: